Prefer setting preferences only within the currently active project
JuliaPackaging/Preferences.jl pull request #37
Opened 2022-04-19 21:47 UTC by staticfloat

Previous to this change, we would search up the environment stack
looking for the project that contains the target package, and set the
preference in there.  This was intended to make it convenient to e.g.
set a `Revise` preference while having an application project activated.
It turns out that the more common problem is actually that a package
wants to set a preference of a sub-package (e.g. `MPI` and
`MPIPreferences`) that may not be a top-level dependent of the currently
active project.

Therefore, we change the behavior of `set_preferences!()` to prefer
adding the target package as an `extras` dependency of the
currently-active project, but maintain the old behavior behind a keyword
argument to `set_preferences!()`.

2022-04-19 22:01 UTC, DilumAluthge commented
Technically breaking?

2022-04-19 22:03 UTC, DilumAluthge requested changes

2022-04-19 22:03 UTC, DilumAluthge commented on Project.toml
> +version = "1.3.0"
```suggestion
version = "2.0.0-DEV"

Unless you know you don't plan on making any other breaking changes anytime soon, in which case you could just set it to `2.0.0` and cut a new release after this PR is merged.
```

2022-04-19 22:08 UTC, staticfloat commented
I'm not really sure this counts as breaking.... I don't think anyone is relying on this implementation detail, and it wasn't even documented.  @vchuravy what do you think?

2022-04-20 04:10 UTC, DilumAluthge commented
Hmmm, if the original behavior wasn't documented, then it's probably not breaking to change the behavior.

2022-04-20 05:28 UTC, vchuravy commented
One could even argue that it's a bug fix since we have in the docs:

> The above snippet first clears the `"compiler_options"` key of any inheriting influence,
then sets a preference option, which guarantees that future loading of that preference
will be exactly what was saved here.  If we wanted to re-enable inheritance from higher
up in the chain, we could do the same but passing `missing` first.

Which didn't work. We would wipe the preferences higher up in the chain instead.

2022-04-20 05:32 UTC, vchuravy approved these changes

2022-04-20 06:51 UTC, merged